import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Montserrat } from "next/font/google";
import MainTemplate from "@/core/components/MainTemplate/MainTemplate";

const montserrat = Montserrat({ subsets: ["latin"], variable: "--font-mons" });

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Brandspark",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`scroll-smooth`}>
      <body className="bg-blackBackground text-white font-secondary">
        <MainTemplate>{children}</MainTemplate>
      </body>
    </html>
  );
}
